Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using coop_atm_locator.Models;
using coop_atm_locator.Backend;
using NetTopologySuite;
using NetTopologySuite.Geometries;

namespace coop_atm_locator.Controllers
{
    public class LocationsController : Controller
    {
        private readonly atmLocator_flatContext _context;
        private LocationsBackend backend;

        public LocationsController(atmLocator_flatContext context, LocationsBackend backend = null)
        {
            _context = context;

            // Fork to allow for mocking out backend
            if (backend != null)
            {
                this.backend = backend;
            }
            else
            {
                this.backend = new LocationsBackend(_context);
            }
        }

        // GET: Locations
        public async Task<IActionResult> Index()
        {
            /*return View(await _context.Locations.ToListAsync());*/

            var cleanResults = await GetCleanViewModel();

            return View(cleanResults);
        }

        [Produces("application/json")]
        public async Task<JsonResult> CardJson()
        {

            var cleanResults = await GetCleanViewModel();

            // get the user's location values in the session cookie
            var Latitude = Request.Cookies["latitude"];
            var Longitude = Request.Cookies["longitude"];

            // if the user blocks cookies then use the tukwila headquarters as default coordinates
            if (string.IsNullOrEmpty(Latitude))
            {
                Latitude = "47.490209";
            }
            if (string.IsNullOrEmpty(Longitude))
            {
                Longitude = "-122.272126";
            }

            // create a new latlng object from the assigned location values
            var point = new PositionModel(Latitude, Longitude);

            // create and object that can pass the user location along with the list of atms to the ajax via json
            var data = new
            {
                point,
                cleanResults.CleanLocationList
            };

            return new JsonResult(data);
        }



        public async Task<CleanLocationViewModel> GetCleanViewModel()
        {
            // get the raw un-parsed values from the locations model
            var dirtyResults = await backend.IndexAsync().ConfigureAwait(false);
            // get the parsed values to eliminate undefined values after processing in the CleanLocationModel
            var cleanResults = new CleanLocationViewModel(dirtyResults);

            // get the user's location values in the session cookie
            var Latitude = Request.Cookies["latitude"];
            var Longitude = Request.Cookies["longitude"];

            // if the user blocks cookies then use the tukwila headquarters as default coordinates
            if (string.IsNullOrEmpty(Latitude))
            {
                Latitude = "47.490209";
            }
            if (string.IsNullOrEmpty(Longitude))
            {
                Longitude = "-122.272126";
            }

            // create a new latlng object from the assigned location values
            var point = new PositionModel(Latitude, Longitude);

            // assign user coordinates from the latlng object
            var geometryFactory = NtsGeometryServices.Instance.CreateGeometryFactory(srid: 4326);
            Point userPoint = geometryFactory.CreatePoint(new Coordinate(point.Lat, point.Lng));

            // update distance value based on user coordinates and reset geometry factory to null before sending
            foreach (var value in cleanResults.CleanLocationList)
            {
                value.MyPoint = geometryFactory.CreatePoint(new Coordinate(value.Position.Lat, value.Position.Lng));
                value.MyDistance = value.MyPoint.Distance(userPoint);
                value.MyPoint = null;
            }

            // sort the clean results list by distance and reduce by range
            cleanResults.CleanLocationList = cleanResults.CleanLocationList.OrderBy(x => x.MyDistance).ToList().GetRange(0, 32);


            return cleanResults;
        }

        /* // GET: Locations/Details/5
         public async Task<IActionResult> Details(string id)
         {
             if (id == null)
             {
                 return NotFound();
             }

             var locations = await _context.Locations
                 .FirstOrDefaultAsync(m => m.Name == id);
             if (locations == null)
             {
                 return NotFound();
             }

             return View(locations);
         }

         // GET: Locations/Create
         public IActionResult Create()
         {
             return View();
         }

         // POST: Locations/Create
         // To protect from overposting attacks, enable the specific properties you want to bind to, for 
         // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
         [HttpPost]
         [ValidateAntiForgeryToken]
         public async Task<IActionResult> Create([Bind("ReferenceId,Name,Address,City,County,State,PostalCode,Country,Phone,Fax,WebAddress,Latitude,Longitude,Hours,RetailOutlet,RestrictedAccess,AcceptDeposit,AcceptCash,EnvelopeRequired,OnMilitaryBase,OnPremise,Surcharge,Access,AccessNotes,InstallationType,HandicapAccess,LocationType,HoursMonOpen,HoursMonClose,HoursTueOpen,HoursTueClose,HoursWedOpen,HoursWedClose,HoursThuOpen,HoursThuClose,HoursFriOpen,HoursFriClose,HoursSatOpen,HoursSatClose,HoursSunOpen,HoursSunClose,HoursDtmonOpen,HoursDtmonClose,HoursDttueOpen,HoursDttueClose,HoursDtwedOpen,HoursDtwedClose,HoursDtthuOpen,HoursDtthuClose,HoursDtfriOpen,HoursDtfriClose,HoursDtsatOpen,HoursDtsatClose,HoursDtsunOpen,HoursDtsunClose,Cashless,DriveThruOnly,LimitedTransactions,MilitaryIdRequired,SelfServiceDevice,SelfServiceOnly")] Locations locations)
         {
             if (ModelState.IsValid)
             {
                 _context.Add(locations);
                 await _context.SaveChangesAsync();
                 return RedirectToAction(nameof(Index));
             }
             return View(locations);
         }

         // GET: Locations/Edit/5
         public async Task<IActionResult> Edit(string id)
         {
             if (id == null)
             {
                 return NotFound();
             }

             var locations = await _context.Locations.FindAsync(id);
             if (locations == null)
             {
                 return NotFound();
             }
             return View(locations);
         }

         // POST: Locations/Edit/5
         // To protect from overposting attacks, enable the specific properties you want to bind to, for 
         // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
         [HttpPost]
         [ValidateAntiForgeryToken]
         public async Task<IActionResult> Edit(string id, [Bind("ReferenceId,Name,Address,City,County,State,PostalCode,Country,Phone,Fax,WebAddress,Latitude,Longitude,Hours,RetailOutlet,RestrictedAccess,AcceptDeposit,AcceptCash,EnvelopeRequired,OnMilitaryBase,OnPremise,Surcharge,Access,AccessNotes,InstallationType,HandicapAccess,LocationType,HoursMonOpen,HoursMonClose,HoursTueOpen,HoursTueClose,HoursWedOpen,HoursWedClose,HoursThuOpen,HoursThuClose,HoursFriOpen,HoursFriClose,HoursSatOpen,HoursSatClose,HoursSunOpen,HoursSunClose,HoursDtmonOpen,HoursDtmonClose,HoursDttueOpen,HoursDttueClose,HoursDtwedOpen,HoursDtwedClose,HoursDtthuOpen,HoursDtthuClose,HoursDtfriOpen,HoursDtfriClose,HoursDtsatOpen,HoursDtsatClose,HoursDtsunOpen,HoursDtsunClose,Cashless,DriveThruOnly,LimitedTransactions,MilitaryIdRequired,SelfServiceDevice,SelfServiceOnly")] Locations locations)
         {
             if (id != locations.Name)
             {
                 return NotFound();
             }

             if (ModelState.IsValid)
             {
                 try
                 {
                     _context.Update(locations);
                     await _context.SaveChangesAsync();
                 }
                 catch (DbUpdateConcurrencyException)
                 {
                     if (!LocationsExists(locations.Name))
                     {
                         return NotFound();
                     }
                     else
                     {
                         throw;
                     }
                 }
                 return RedirectToAction(nameof(Index));
             }
             return View(locations);
         }

         // GET: Locations/Delete/5
         public async Task<IActionResult> Delete(string id)
         {
             if (id == null)
             {
                 return NotFound();
             }

             var locations = await _context.Locations
                 .FirstOrDefaultAsync(m => m.Name == id);
             if (locations == null)
             {
                 return NotFound();
             }

             return View(locations);
         }

         // POST: Locations/Delete/5
         [HttpPost, ActionName("Delete")]
         [ValidateAntiForgeryToken]
         public async Task<IActionResult> DeleteConfirmed(string id)
         {
             var locations = await _context.Locations.FindAsync(id);
             _context.Locations.Remove(locations);
             await _context.SaveChangesAsync();
             return RedirectToAction(nameof(Index));
         }*/

        private bool LocationsExists(string id)
        {
            return _context.Locations.Any(e => e.Name == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - COOP ATM Locator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="https://kit.fontawesome.com/44effbaeaf.js" crossorigin="anonymous"></script>
    @*<script src="https://kit.fontawesome.com/e1e75ed5a3.js" crossorigin="anonymous"></script>*@
    <link rel="stylesheet" href="https://kit-free.fontawesome.com/releases/latest/css/free.min.css" media="all">
    <link rel="stylesheet" href="https://kit-free.fontawesome.com/releases/latest/css/free-v4-font-face.min.css" media="all">
    <link rel="stylesheet" href="https://kit-free.fontawesome.com/releases/latest/css/free-v4-shims.min.css" media="all">

    @*Display custom favicon*@
    <link rel="icon" type="image/x-icon" href="~/assets/favicon_maphawks.ico">

    @* This is a dev only key with very limited functionality:  *@
    <script src="https://maps.googleapis.com/maps/api/js?key={your-api-key}&libraries=places" async defer></script>



    <!--call google map function without the button-->
    <script>
        window.onload = function () {
            initMap();
        }
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Locations" asp-action="Index"><img id="nav-logo" src="~/assets/maphawks_logo_horizontal_on_white.png" alt="maphawks" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Locations" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - COOP ATM Locator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="~/js/mapMethods.js"></script>
    <script type="text/javascript" src="~/js/map.js"></script>
    <script type="text/javascript" src="~/js/filterCards.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>